Repository AT-PHPIntership/borrow-book, pull requests merged in 2018-06, with the labels that each got.

#77 sort book
  app/Http/Controllers/Admin/BookController.php
  app/Models/Book.php
  config/columnsortable.php
  resources/views/admin/books/index.blade.php
Labels: in-review, task, week3

#75 Fix Paginate when sort And unitest sort user
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/SortUserTest.php
Labels: in-review, task, week3

#76 write unit test create category
  app/Http/Controllers/Admin/CategoryController.php
  tests/Browser/Pages/Backend/CreateCategoryTest.php
Labels: in-review, task, week3

#78 Layout and update category
  app/Http/Controllers/Admin/CategoryController.php
  public/js/updateCategory.js
  resources/lang/en/category.php
  resources/views/admin/categories/index.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
Labels: in-review, task, week3

#81 Unit test update category
  public/js/updateCategory.js
  resources/lang/en/book.php
  resources/lang/en/post.php
  resources/lang/en/user.php
  resources/views/admin/categories/index.blade.php
  tests/Browser/Pages/Backend/CreateUserTest.php
  tests/Browser/Pages/Backend/UpdateCategoryTest.php
Labels: in-review, task, week4

#80 laravel passport and fix path Admin(login, logout)
  app/Models/User.php
  app/Providers/AuthServiceProvider.php
  composer.json
  composer.lock
  config/auth.php
  resources/views/admin/layouts/partials/header.blade.php
  resources/views/auth/login.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: in-review, task, week4

#82 Unitest sort book
  resources/views/admin/books/index.blade.php
  tests/Browser/Pages/Backend/SortBookTest.php
Labels: in-review, task, week4

#86 create layout api documentation
  docs/api-references/api.md
  resources/views/api-docs-builders/index.blade.php
  resources/views/api-docs.blade.php
  routes/web.php
Labels: in-review, task, week4

#84 Layout header footer and master page
  public/js/modernizr-2.6.2.min.js
  public/js/owl.carousel.min.js
  resources/views/layouts/master.blade.php
  resources/views/layouts/partials/footer.blade.php
  resources/views/layouts/partials/header.blade.php
  resources/views/layouts/partials/scripts.blade.php
  resources/views/layouts/partials/styles.blade.php
  resources/views/welcome.blade.php
  tests/Browser/ExampleTest.php
Labels: in-review, task, week4

#85 Delete category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
  database/migrations/2018_06_05_031948_update_category_table.php
  resources/lang/en/category.php
  resources/views/admin/categories/index.blade.php
  tests/Browser/Pages/Backend/UpdateCategoryTest.php
Labels: in-review, task, week4

#87 sort category
  app/Http/Controllers/Admin/CategoryController.php
  app/Models/Category.php
  resources/views/admin/categories/index.blade.php
Labels: in-review, task, week4

#88 Fix layout side bar and index category
  resources/views/admin/categories/index.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
Labels: in-review, task, week4

#89 create layout login user
  app/Http/Controllers/API/LoginController.php
  app/Http/Controllers/ApiController.php
  app/Http/Controllers/User/Auth/LoginController.php
  app/Traits/ApiResponser.php
  resources/views/layouts/master.blade.php
  resources/views/user/auth/login.blade.php
  routes/web.php
Labels: in-review, task, week4

#91 Unitest sort category
  resources/views/admin/categories/index.blade.php
  tests/Browser/Pages/Backend/SortCategoryTest.php
Labels: in-review, task, week4

#92 document for api login
  docs/api-references/login.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week4

#90 Unit test delete category
  app/Models/Category.php
  tests/Browser/Pages/Backend/DeleteCategoryTest.php
Labels: in-review, task, week4

#93 docs api get list books
  docs/api-references/book.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week4

#94 fix api login
  app/Http/Controllers/API/LoginController.php
Labels: in-review, task, week4

#97 Api get book on homepage
  app/Http/Controllers/API/BookController.php
  app/Models/Book.php
  app/Traits/ApiResponser.php
  routes/api.php
Labels: in-review, task, week4

#95 write api get all category
  docs/api-references/book.md
  docs/api-references/category.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week4

#99 api show book
  app/Http/Controllers/API/BookController.php
  app/Models/Book.php
Labels: in-review, task, week4

#98 create docs api show detail book
  docs/api-references/book.md
Labels: in-review, task, week4

#96 Fix docs get list books
  docs/api-references/book.md
Labels: bug, in-review, task, week4

#102 api show detail book
  app/Http/Controllers/API/BookController.php
  routes/api.php
Labels: in-review, task, week5

#101 api category
  app/Http/Controllers/API/CategoryController.php
  app/Traits/ApiResponser.php
  routes/api.php
Labels: in-review, task, week5

#103 Api get list posts following book
  app/Http/Controllers/API/PostController.php
  app/Models/User.php
  app/Traits/ApiResponser.php
  docs/api-references/book.md
  routes/api.php
Labels: in-review, task, week5

#104 use api show list book homepage
  app/Models/ImageBook.php
  public/css/icomoon.css
  public/js/showListBook.js
  resources/views/layouts/master.blade.php
  resources/views/layouts/partials/banner.blade.php
  resources/views/layouts/partials/styles.blade.php
  resources/views/welcome.blade.php
Labels: in-review, task, week5

#105 Write docs and fix api get list posts
  app/Http/Controllers/API/PostController.php
  app/Models/Post.php
  docs/api-references/post.md
Labels: in-review, task, week5

#109 docs search book by filter
  docs/api-references/book.md
Labels: in-review, task, week5

#107 Unit test api get list posts
  docs/api-references/book.md
  docs/api-references/post.md
  tests/Feature/ApiGetListPostsOfBookTest.php
Labels: in-review, task, week5

#106 add function paginate page
  public/js/jquery.twbsPagination.min.js
  public/js/showListBook.js
  resources/views/layouts/partials/scripts.blade.php
Labels: in-review, task, week5

#108 Api search book by filter
  app/Http/Controllers/API/BookController.php
  app/Models/Book.php
  app/Traits/FilterTrait.php
Labels: in-review, task, week5

#112 Unit test api get list post
  tests/Feature/ApiGetListPostsOfBookTest.php
Labels: in-review, task, week5

#115 docs create post api
  docs/api-references/post.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week5

#117 Show api detail book
  app/Http/Controllers/BookController.php
  public/css/style.css
  public/js/showDetailBook.js
  resources/views/layouts/partials/scripts.blade.php
  resources/views/layouts/partials/styles.blade.php
  resources/views/user/books/show.blade.php
  routes/web.php
  tests/Feature/ApiShowBookTest.php
Labels: in-review, task, week5

#118 Api create comment review
  app/Http/Controllers/API/PostController.php
  app/Http/Requests/CreatePostRequest.php
  database/migrations/2018_06_15_034355_update_books_table.php
  database/migrations/2018_06_15_090846_update_posts_table.php
  public/js/showListCategories.js
  resources/views/layouts/partials/scripts.blade.php
  resources/views/welcome.blade.php
  routes/api.php
Labels: in-review, task, week5

#120 Use api filter
  app/Http/Controllers/BookController.php
  app/Models/Book.php
  public/js/showListBook.js
  public/js/showListCategories.js
  resources/lang/en/listBook.php
  resources/views/layouts/partials/scripts.blade.php
  resources/views/user/books/index.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: in-review, task, week6

#121 Test api login user
  tests/Feature/ApiLoginTest.php
Labels: in-review, task, week6

#124 use api show post
  public/images/loader.gif
  public/js/posts.js
  resources/lang/en/book.php
  resources/views/user/books/show.blade.php
Labels: in-review, task, week6

#114 doc delete post api
  docs/api-references/post.md
Labels: in-review, task, week5

#125 Docs register
  docs/api-references/register.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week6

#122 Api delete comment review
  app/Http/Controllers/API/PostController.php
  routes/api.php
Labels: in-review, task, week6

#123 docs profile user
  docs/api-references/profile.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week6

#127 Docs add borrow and fix title docs
  docs/api-references/book.md
  docs/api-references/borrow.md
  docs/api-references/category.md
  docs/api-references/post.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week6

#128 docs update post
  docs/api-references/post.md
Labels: in-review, task, week6

#130 use api register
  app/Http/Controllers/User/Auth/LoginController.php
  app/Models/User.php
  public/js/register.js
  resources/lang/en/register.php
  resources/views/layouts/master.blade.php
  resources/views/layouts/partials/header.blade.php
  resources/views/layouts/partials/scripts.blade.php
  resources/views/user/auth/register.blade.php
  routes/web.php
Labels: in-review, task, week6

#131 Fix api get list post
  app/Http/Controllers/API/PostController.php
  tests/Feature/ApiGetListPostsOfBookTest.php
Labels: in-review, task, week6

#129 docs get post following user-id
  docs/api-references/post.md
Labels: in-review, task, week6

#132 write api borrow book
  app/Http/Controllers/API/BorrowController.php
  database/migrations/2018_06_21_025203_update_borrowes_table.php
  docs/api-references/borrow.md
  resources/lang/en/borrow.php
  routes/api.php
Labels: in-review, task, week6

#135 delete post
  app/Http/Controllers/API/PostController.php
  public/js/posts.js
Labels: in-review, task, week6

#137 write api get post following user
  app/Http/Controllers/API/UserController.php
  routes/api.php
Labels: in-review, task, week6

#133 api profile user
  app/Http/Controllers/API/UserController.php
  routes/api.php
Labels: in-review, task, week6

#134 Use api show book in homepage
  app/Traits/ApiResponser.php
  public/css/style.css
  public/js/showListNewBook.js
  resources/lang/en/homepage.php
  resources/views/welcome.blade.php
Labels: in-review, task, week6

#138 Fix delete post
  app/Http/Controllers/API/PostController.php
Labels: bug, in-review, task, week6

#139 Unitest filter book
  tests/Feature/FilterBookTest.php
Labels: in-review, task, week6

#140 api update post
  app/Http/Controllers/API/PostController.php
  resources/lang/en/post.php
  routes/api.php
Labels: in-review, task, week6

#143 Layout add borrow
  app/Http/Controllers/CartController.php
  public/css/style.css
  public/js/showDetailBook.js
  public/js/showListBook.js
  public/js/showListNewBook.js
  resources/lang/en/cart.php
  resources/lang/en/homepage.php
  resources/views/layouts/master.blade.php
  resources/views/layouts/partials/banner2.blade.php
  resources/views/layouts/partials/header.blade.php
  resources/views/user/books/index.blade.php
  resources/views/user/cart/index.blade.php
  routes/web.php
Labels: in-review, task, week6

#145 Use api add comment and review
  public/css/style.css
  public/js/posts.js
  resources/lang/en/post.php
  resources/views/user/books/show.blade.php
Labels: in-review, task, week6

#148 Fix layout delete post
  public/js/posts.js
Labels: bug, task, week6

#154 Docs get list borrow following user
  docs/api-references/borrow.md
Labels: in-review, task, week6

#151 Use api profile user
  app/Http/Controllers/UserController.php
  public/css/style.css
  public/js/homepage.js
  public/js/message.js
  public/js/userProfile.js
  resources/lang/en/auth.php
  resources/views/user/profile/index.blade.php
  routes/web.php
Labels: in-review, task, week6

#155 validation borrow
  app/Http/Controllers/API/BorrowController.php
  app/Http/Requests/Api/BorrowBookRequest.php
  public/js/viewCart.js
Labels: in-review, task, week6

#157 Unitest category
  tests/Feature/ApiCategoryTest.php
Labels: in-review, task, week6

#161 Unit test add post
  app/Http/Controllers/API/PostController.php
  tests/Feature/ApiAddPostTest.php
Labels: in-review, task, week6

#159 Use api update post
  public/css/style.css
  public/js/posts.js
  resources/lang/en/post.php
  resources/views/user/books/show.blade.php
Labels: in-review, task, week6

#136 Add url to get list books following category
  public/css/style.css
  public/js/showListBook.js
  public/js/showListCategories.js
Labels: in-review, task, week6
