Repository AT-PHPIntership/borrow-book, pull requests merged in 2018-07, with the labels that each got.

#168 Fix update post
  public/js/posts.js
  resources/views/user/books/show.blade.php
Labels: bug, in-review, task, week6

#163 Api get list borrows
  app/Http/Controllers/API/BorrowController.php
  public/js/showListCategories.js
  routes/api.php
Labels: in-review, task, week6

#164 Unitest get post following user
  tests/Feature/ApiGetListPostOfUserTest.php
Labels: in-review, task, week6

#171 fix show error and confirm of delete post
  public/js/posts.js
  public/js/userPost.js
  resources/views/user/books/show.blade.php
Labels: in-review, task, week7

#172 write unit test api delete post
  tests/Feature/ApiDeletePost.php
Labels: in-review, task, week7

#173 Docs cancel borrow
  docs/api-references/borrow.md
Labels: in-review, task, week7

#180 Api cancel borrow
  app/Http/Controllers/API/BorrowController.php
  resources/lang/en/borrow.php
  routes/api.php
Labels: in-review, task, week7

#179 Fix docs cancel borrow
  docs/api-references/borrow.md
Labels: in-review, task, week7

#183 Unit test add borrow book
  tests/Feature/ApiCreateBorrowTest.php
Labels: in-review, task, week7

#175 Unitest update post
  app/Http/Controllers/API/PostController.php
  app/Http/Requests/PostRequest.php
  tests/Feature/ApiUpdatePostTest.php
Labels: in-review, task, week7

#185 Update docs cancel borrow
  docs/api-references/borrow.md
Labels: in-review, task, week7

#187 update note when cancel borrow
  app/Http/Controllers/API/BorrowController.php
  app/Models/Borrow.php
  app/Models/Note.php
  app/Models/User.php
  database/migrations/2018_07_06_015354_create_notes_table.php
Labels: in-review, task, week7

#188 Use api cancel
  public/js/message.js
  public/js/userBorrow.js
  resources/lang/en/auth.php
  resources/lang/en/user.php
  resources/views/user/profile/index.blade.php
Labels: in-review, task, week8

#189 send mail reminder give back book
  app/Console/Commands/SendMailReminder.php
  app/Console/Kernel.php
  app/Jobs/SendMailsJob.php
  app/Mail/BorrowedBookMail.php
  database/migrations/2018_07_09_022828_create_jobs_table.php
  database/migrations/2018_07_09_063508_update3_borrowes_table.php
  resources/lang/en/borrow.php
  resources/views/admin/borrows/mailsBorrowed.blade.php
Labels: in-review, task, week8

#191 Layout reset password
  resources/lang/en/resetPassword.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/layouts/master.blade.php
  resources/views/layouts/partials/footer.blade.php
  resources/views/user/auth/login.blade.php
  routes/web.php
Labels: in-review, task, week8

#192 Send mail recommend book
  app/Console/Commands/SendMailRecommend.php
  app/Console/Kernel.php
  app/Jobs/SendMailRecommendJob.php
  app/Jobs/SendMailsJob.php
  app/Mail/RecommendBookMail.php
  app/Models/User.php
  database/migrations/2018_07_10_024455_update_users_table.php
  resources/views/admin/books/mailsRecommend.blade.php
Labels: in-review, task, week8

#194 Docs reset password
  docs/api-references/reset_password.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week8

#195 Api reset password
  app/Http/Controllers/API/ForgotPasswordController.php
  app/Http/Controllers/API/ResetPasswordController.php
  routes/api.php
  routes/web.php
Labels: in-review, task, week8

#197 Use api reset password
  public/js/resetPassword.js
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/user/auth/login.blade.php
Labels: in-review, task, week8

#199 scan barcode
  app/Http/Controllers/Admin/BookController.php
  database/factories/ModelFactory.php
  database/migrations/2018_07_12_014352_add_column_barcode_in_books_table.php
  public/js/readBarcode.js
  resources/views/admin/books/index.blade.php
  routes/web.php
Labels: in-review, task, week8

#196 Unit test cancel borrow
  database/factories/ModelFactory.php
  tests/Feature/ApiCancelBorrow.php
  tests/Feature/ApiGetListBorrowTest.php
  tests/Feature/ApiUpdatePostTest.php
Labels: in-review, task, week8

#184 recommend book
  app/Models/Book.php
  app/Traits/FilterTrait.php
  public/js/addCart.js
  public/js/recommendBook.js
  public/js/showDetailBook.js
  public/js/showListBook.js
  public/js/showListNewBook.js
  public/js/viewCart.js
  resources/lang/en/cart.php
  resources/lang/en/homepage.php
  resources/views/layouts/partials/scripts.blade.php
  resources/views/user/books/show.blade.php
  resources/views/user/cart/index.blade.php
  resources/views/welcome.blade.php
Labels: in-review, task, week7

#202 Docs markdown book
  docs/api-references/favorite.md
  resources/views/api-docs-builders/index.blade.php
Labels: in-review, task, week9

#203 Api favorite book
  app/Http/Controllers/API/FavoriteController.php
  resources/lang/en/favorite.php
  routes/api.php
Labels: in-review, task, week9

#206 Api delete favorite book
  app/Http/Controllers/API/FavoriteController.php
  resources/lang/en/favorite.php
  routes/api.php
Labels: in-review, task, week9
