Repository AT-PHPIntership/borrow-book, pull requests merged in 2018-05, with the labels that each got.

#2 Create migration
  .bowerrc
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2018_05_14_030015_create_categories_table.php
  database/migrations/2018_05_14_030300_create_books_table.php
  database/migrations/2018_05_14_030833_create_image_books_table.php
  database/migrations/2018_05_14_031108_create_posts_table.php
  database/migrations/2018_05_14_031453_create_favorites_table.php
  database/migrations/2018_05_14_031708_create_borrowes_table.php
  database/migrations/2018_05_14_031950_create_borrow_details_table.php
  database/migrations/2018_05_14_032651_create_ratings_table.php
Labels: in-review, task, week1

#3 Create Models and Relationship
  app/Models/Book.php
  app/Models/Borrow.php
  app/Models/BorrowDetail.php
  app/Models/Category.php
  app/Models/Favorite.php
  app/Models/ImageBook.php
  app/Models/Post.php
  app/Models/Rating.php
  app/Models/User.php
  app/User.php
Labels: in-review, task, week1

#4 template admin index
  composer.lock
  resources/lang/en/admin.php
  resources/views/admin/index.blade.php
  resources/views/admin/layouts/admin.blade.php
  resources/views/admin/layouts/partials/footer.blade.php
  resources/views/admin/layouts/partials/header.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/layouts/partials/scripts.blade.php
  resources/views/admin/layouts/partials/styles.blade.php
  routes/web.php
Labels: in-review, task, week1

#7 create factory and seeder
  app/Models/Borrow.php
  app/Models/Post.php
  app/Models/User.php
  database/factories/ModelFactory.php
  database/factories/UserFactory.php
  database/seeds/DatabaseSeeder.php
Labels: in-review, task, week1

#6 get list users
  app/Http/Controllers/UserController.php
  routes/web.php
Labels: in-review, task, week1

#8 create validation create user
  app/Http/Requests/CreateUserRequest.php
Labels: done, task, week1

#9 layout create users
  resources/lang/en/admin.php
  resources/lang/en/user.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/users/create.blade.php
  routes/web.php
Labels: task, week1

#10 Show list user
  app/Http/Controllers/Admin/UserController.php
  app/Models/ImageBook.php
  app/Models/User.php
  config/image.php
  database/factories/ModelFactory.php
  database/factories/UserFactory.php
  resources/lang/en/user.php
  resources/views/admin/users/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#11 Layout update user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/users/update.blade.php
  routes/web.php
Labels: in-review, task, week1

#14 Save user
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/CreateUserRequest.php
  app/Models/User.php
  resources/lang/en/admin.php
  resources/lang/en/user.php
  resources/views/admin/layouts/partials/errors.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/layouts/partials/messages.blade.php
  resources/views/admin/users/create.blade.php
  resources/views/admin/users/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#13 unit test show list user
  tests/Browser/Pages/Backend/ShowListUserTest.php
  tests/DuskTestCase.php
Labels: in-review, task, week1

#17 create layout list book
  app/Http/Controllers/Admin/BookController.php
  resources/lang/en/book.php
  resources/views/admin/books/index.blade.php
  routes/web.php
Labels: in-review, task, week1

#19 Send mail
  app/Http/Controllers/Admin/UserController.php
  app/Mail/CreateUserMail.php
  config/mail.php
  resources/views/admin/users/mails.blade.php
Labels: in-review, task, week1

#12 Get user info
  app/Http/Controllers/Admin/UserController.php
  app/Http/Requests/UpdateUserRequest.php
  config/image.php
  resources/views/admin/users/update.blade.php
Labels: in-review, task, week1

#18 Get and show list books
  app/Http/Controllers/Admin/BookController.php
  config/image.php
  database/factories/ModelFactory.php
  resources/views/admin/books/index.blade.php
Labels: in-review, task, week1

#20 Unit test show list books
  tests/Browser/Pages/Backend/ShowListBookTest.php
Labels: in-review, task, week1

#21 Save update user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/users/update.blade.php
Labels: in-review, task, week1

#22 layout create book
  app/Http/Controllers/Admin/BookController.php
  resources/lang/en/book.php
  resources/views/admin/books/create.blade.php
Labels: in-review, task, week1

#24 Delete user
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/users/index.blade.php
Labels: in-review, task, week1

#23 Validation and save book
  app/Http/Controllers/Admin/BookController.php
  app/Http/Requests/CreateBookRequest.php
  app/Models/Book.php
  composer.json
  composer.lock
  database/migrations/2018_05_18_012509_update_default_image_books_table.php
  resources/lang/en/book.php
  resources/views/admin/books/create.blade.php
Labels: in-review, task, week1

#28 write unit test create book
  tests/Browser/Pages/Backend/CreateBookTest.php
Labels: in-review, task, week1

#25 Unitest update users
  composer.lock
  resources/lang/en/user.php
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/ShowListBookTest.php
  tests/Browser/Pages/Backend/UpdateUserTest.php
  tests/Browser/Pages/Backend/testing_file/ahihi.txt
Labels: in-review, task, week2

#29 testing create user
  app/Http/Controllers/Admin/UserController.php
  database/migrations/2018_05_22_070708_update_default_image_users_table.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  tests/Browser/Pages/Backend/CreateUserTest.php
Labels: in-review, task, week2

#31 Create login, logout and register
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/RegisterController.php
  config/auth.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/register.blade.php
  resources/views/layouts/app.blade.php
  resources/views/welcome.blade.php
  routes/web.php
Labels: in-review, task, week2

#35 layout borrow book
  app/Http/Controllers/Admin/BorrowController.php
  resources/lang/en/borrow.php
  resources/views/admin/borrows/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#33 Testing delete user
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/DeleteUserTest.php
Labels: in-review, task, week2

#32 Login with role
  app/Http/Controllers/Auth/LoginController.php
  app/Http/Controllers/Auth/ResetPasswordController.php
  app/Http/Kernel.php
  app/Http/Middleware/AdminMiddleware.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Browser/ExampleTest.php
  tests/Browser/Pages/Backend/CreateBookTest.php
  tests/Browser/Pages/Backend/CreateUserTest.php
  tests/Browser/Pages/Backend/DeleteUserTest.php
  tests/Browser/Pages/Backend/ShowListBookTest.php
  tests/Browser/Pages/Backend/ShowListUserTest.php
  tests/Browser/Pages/Backend/UpdateUserTest.php
  tests/DuskTestCase.php
Labels: in-review, task, week2

#34 Delete book
  app/Http/Controllers/Admin/BookController.php
  resources/lang/en/book.php
  resources/views/admin/books/index.blade.php
Labels: in-review, task, week2

#36 get and show list borrow book
  app/Http/Controllers/Admin/BorrowController.php
  public/css/image.css
  resources/lang/en/borrow.php
  resources/views/admin/borrows/index.blade.php
Labels: in-review, task, week2

#37 Unit test show borrow book
  app/Http/Middleware/AdminMiddleware.php
  resources/views/admin/borrows/index.blade.php
  tests/Browser/Pages/Backend/ShowListBorrowTest.php
Labels: in-review, task, week2

#40 Layout list post
  app/Http/Controllers/Admin/PostController.php
  resources/lang/en/post.php
  resources/views/admin/posts/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#41 Unit test search user
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/SearchUserTest.php
Labels: in-review, task, week2

#42 Get and show list post
  app/Http/Controllers/Admin/PostController.php
  resources/lang/en/post.php
  resources/views/admin/posts/index.blade.php
Labels: in-review, task, week2

#46 unitest list post
  tests/Browser/Pages/Backend/ShowListPostTest.php
Labels: in-review, task, week2

#52 fix pagination in search book
  app/Http/Controllers/Admin/BookController.php
  resources/views/admin/books/index.blade.php
Labels: in-review, task, week2

#27 Get and save book
  app/Http/Controllers/Admin/BookController.php
  app/Http/Controllers/Admin/ImageBookController.php
  composer.json
  composer.lock
  config/app.php
  public/css/image.css
  public/js/deleteImage.js
  public/js/message.js
  resources/lang/en/book.php
  resources/views/admin/books/edit.blade.php
  resources/views/admin/layouts/admin.blade.php
  routes/web.php
Labels: in-review, task, week2

#48 Delete post
  app/Http/Controllers/Admin/PostController.php
  resources/lang/en/post.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/posts/index.blade.php
Labels: in-review, task, week2

#50 unitest delete post
  tests/Browser/Pages/Backend/DeletePostTest.php
Labels: in-review, task, week2

#49 add name, avatar with header,left-bar and logout
  public/js/main.js
  resources/lang/en/auth.php
  resources/lang/en/user.php
  resources/views/admin/layouts/partials/header.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/layouts/partials/scripts.blade.php
  resources/views/admin/layouts/partials/styles.blade.php
Labels: in-review, task, week2

#47 Unit test search book
  app/Http/Controllers/Admin/BookController.php
  resources/lang/en/book.php
  resources/lang/en/search.php
  resources/views/admin/books/index.blade.php
  resources/views/admin/layouts/partials/message_search.blade.php
  resources/views/admin/layouts/partials/messages.blade.php
  tests/Browser/Pages/Backend/DeleteUserTest.php
  tests/Browser/Pages/Backend/SearchBookTest.php
Labels: in-review, task, week2

#53 fix error layout
  public/css/image.css
  resources/lang/en/borrow.php
  resources/views/admin/books/edit.blade.php
  resources/views/admin/books/index.blade.php
  resources/views/admin/borrows/index.blade.php
  resources/views/admin/layouts/partials/left-bar.blade.php
  resources/views/admin/posts/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/admin/users/update.blade.php
Labels: bug, in-review, week2

#58 Approve status ajax
  app/Http/Controllers/Admin/PostController.php
  composer.lock
  resources/views/admin/layouts/admin.blade.php
  resources/views/admin/layouts/partials/styles.blade.php
  resources/views/admin/posts/index.blade.php
  routes/web.php
Labels: in-review, task, week3

#61 fix relationship borrow, fix seed
  app/Models/Borrow.php
  database/factories/ModelFactory.php
  database/seeds/BorrowDetailsTableSeeder.php
  database/seeds/DatabaseSeeder.php
Labels: bug, in-review, week3

#60 Fix delete user
  app/Http/Controllers/Admin/BookController.php
  app/Http/Controllers/Admin/PostController.php
  app/Http/Controllers/Admin/UserController.php
  app/Models/Borrow.php
  resources/lang/en/user.php
  resources/views/admin/layouts/partials/messages.blade.php
  resources/views/admin/users/index.blade.php
Labels: bug, in-review, week3

#63 Layout and Show detail book
  app/Http/Controllers/Admin/BookController.php
  resources/lang/en/book.php
  resources/views/admin/books/index.blade.php
  resources/views/admin/books/show.blade.php
Labels: in-review, task, week3

#57 layout detail borrower book
  app/Http/Controllers/Admin/UserController.php
  resources/lang/en/user.php
  resources/views/admin/users/borrowDetail.blade.php
  routes/web.php
Labels: in-review, task, week2

#62 fix search user and unit test
  app/Http/Controllers/Admin/UserController.php
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/SearchBookTest.php
  tests/Browser/Pages/Backend/SearchUserTest.php
Labels: bug, in-review, week3

#66 Unit test detail book
  resources/views/admin/books/index.blade.php
  resources/views/admin/books/show.blade.php
  tests/Browser/Pages/Backend/DetailBookTest.php
Labels: in-review, task, week3

#59 write unit test update book
  resources/views/admin/books/index.blade.php
  tests/Browser/Pages/Backend/UpdateBookTest.php
Labels: in-review, task, week3

#54 create layout show category
  app/Http/Controllers/Admin/CategoryController.php
  resources/lang/en/category.php
  resources/views/admin/categories/index.blade.php
  routes/web.php
Labels: in-review, task, week2

#68 Layout statistical
  public/css/image.css
  resources/lang/en/statistical.php
  resources/views/admin/index.blade.php
Labels: in-review, task, week3

#67 update status borrow
  app/Http/Controllers/Admin/BorrowController.php
  public/js/message.js
  public/js/updateStatusBorrow.js
  resources/lang/en/borrow.php
  resources/views/admin/books/edit.blade.php
  resources/views/admin/borrows/index.blade.php
  resources/views/admin/layouts/partials/scripts.blade.php
  routes/web.php
Labels: in-review, task, week3

#69 Sort User By Name
  app/Http/Controllers/Admin/UserController.php
  app/Models/User.php
  composer.json
  composer.lock
  config/app.php
  config/columnsortable.php
  resources/views/admin/users/index.blade.php
  tests/Browser/Pages/Backend/UpdateUserTest.php
Labels: in-review, task, week3

#55 Get and show list category
  app/Http/Controllers/Admin/CategoryController.php
  resources/lang/en/category.php
  resources/views/admin/categories/index.blade.php
Labels: in-review, task, week2

#56 Layout and create category
  app/Http/Controllers/Admin/CategoryController.php
  app/Http/Requests/CategoryRequest.php
  resources/lang/en/category.php
  resources/views/admin/categories/index.blade.php
Labels: in-review, task, week2

#73 Sort user by email
  app/Http/Controllers/Admin/UserController.php
  app/Models/User.php
  config/columnsortable.php
  resources/views/admin/users/index.blade.php
Labels: in-review, task, week3

#71 Get data statistical
  app/Http/Controllers/Admin/HomeController.php
  public/css/image.css
  resources/lang/en/statistical.php
  resources/views/admin/index.blade.php
  resources/views/admin/layouts/partials/header.blade.php
  routes/web.php
Labels: in-review, task, week3

#74 Unit test statistical
  resources/views/admin/index.blade.php
  tests/Browser/Pages/Backend/HomeTest.php
Labels: in-review, task, week3
